os:
  - linux

env:
  - TESTOS=win32
  - TESTOS=linux

cache: apt

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 800x600x16"

before_script:
  - sudo add-apt-repository -y ppa:pipelight/stable
  - sudo apt-get update -qq
  - sudo apt-get install -y --install-recommends wine-staging wine-staging-compat subversion wget
  - wget https://dl.dropboxusercontent.com/u/38458267/msys2/msys2-base-i686-20150512-20150731.deb
  - sudo dpkg -i msys2-base-i686-20150512-20150731.deb
  - msys2init
  - msys2run "pacman -S --needed --noconfirm gettext rsync"
  - msys2run "pacman -S --needed --noconfirm mingw-w64-i686-toolchain"
  - msys2run "pacman -S --needed --noconfirm mingw-w64-i686-libidn mingw-w64-i686-openssl mingw-w64-i686-pcre"

language: c

compiler:
  - gcc

script:
  - mingw32run "./bootstrap"
  - mingw32run "./configure --target=mingw32 --host=mingw32 --build=mingw32 --with-ssl=openssl"
  - mingw32run "make"
